# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f353be303236e754b09ed74dfcfff03619ff727df17c25be3cdd71db2b3b507747064c4e2035df945ccca659db9166132b258849fa7e49b29645c99bfc7475d1

test:
  secret_key_base: 7a6795fa028f5b039fdfc024db569735116e660a47f5859bf279591fc4ce2d27cd4c54ec9e03c0e36bdf097c5f28d2e59d2bd488e5f0952fcb2f9fbce40796c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7a6795fa028f5b039fdfc024db569735116e660a47f5859bf279591fc4ce2d27cd4c54ec9e03c0e36bdf097c5f28d2e59d2bd488e5f0952fcb2f9fbce40796c5
